apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: myjenkins-pvc
 namespace: myjenkins
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
 storageClassName: slow
 volumeName: myjenkins-pv
