apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins-pvc
 namespace: jenkins
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
 storageClassName: slow
 volumeName: jenkins-pv
